import Link from 'next/link';
import { BookCover } from '@/components/notebook/book-cover';
import { BookCard } from '@/components/catalogue/book-card';
import { Section, SectionHeader } from '@/components/ui/section';
import { ButtonLink } from '@/components/ui/button';
import { Reveal } from '@/components/ui/reveal';
import { frenchBooks, frenchFaqs, features } from '@/lib/french';
import { flagship, catalogueStats } from '@/lib/catalogue';

export function FrenchHome() {
  const book = frenchBooks.find(b => b.id === flagship.id)!;
  return <>
    <section id="top" className="shell pt-36 pb-24 md:pt-44 md:pb-32">
      <div className="grid items-center gap-16 lg:grid-cols-12">
        <div className="lg:col-span-7"><p className="type-eyebrow">Médecine · Pharmacie · Chirurgie dentaire</p><h1 className="type-display mt-7 text-[clamp(3.75rem,13vw,10.5rem)]">THE WIZ</h1><p className="type-lead mt-8 max-w-lg">Les carnets conçus pour aider les étudiants en santé à mieux apprendre.</p><ul className="mt-10 space-y-2 text-ink-72"><li>Des résumés manuscrits de qualité.</li><li>Des explications visuelles claires.</li><li>Des pages pour vos propres notes.</li><li>Un carnet par matière, pour chaque année.</li></ul><div className="mt-12 flex flex-wrap gap-3"><ButtonLink href="#order">Commander</ButtonLink><ButtonLink href="/fr/books" variant="outline">Voir les livres</ButtonLink></div><dl className="mt-14 flex flex-wrap gap-8 border-t border-ink-08 pt-7">{[['Spécialités', '3'], ['Années couvertes', '16'], ['Éditions prévues', String(catalogueStats.total)]].map(([label,value]) => <div key={label}><dt className="text-xs text-ink-56">{label}</dt><dd className="mt-2 text-2xl">{value}</dd></div>)}</dl></div>
        <div className="flex justify-center py-12 lg:col-span-5"><BookCover book={book} locale="fr" width="min(19rem, 65vw)" /></div>
      </div>
    </section>
    <Section id="why"><div className="shell"><SectionHeader eyebrow="Pourquoi The Wiz" title={<>Moins de dispersion.<br /><span className="text-ink-40">Plus de compréhension.</span></>} intro="L’essentiel de vos cours, organisé pour vous laisser le temps de comprendre et de progresser." /><div className="mt-16 grid gap-8 md:grid-cols-3">{[
      ['01', 'Des résumés structurés', 'Chaque chapitre est réorganisé en notes concises, centrées sur l’essentiel.'],
      ['02', 'De la place pour réfléchir', 'Chaque résumé est suivi de pages vierges pour vos ajouts, vos corrections et vos notes de cours.'],
      ['03', 'Conçu pour votre année', 'Chaque édition suit le programme de son année et de sa spécialité.'],
    ].map(([n,title,body]) => <Reveal key={n} className="border-t border-ink-12 pt-8"><p className="type-eyebrow">{n}</p><h3 className="mt-7 text-2xl">{title}</h3><p className="mt-4 leading-relaxed text-ink-56">{body}</p></Reveal>)}</div></div></Section>
    <Section id="inside"><div className="shell"><SectionHeader eyebrow="À l’intérieur" title={<>L’essentiel, au bon endroit.<br /><span className="text-ink-40">Vos idées, juste à côté.</span></>} intro="Des résumés lisibles, des repères visuels et de l’espace pour faire le lien avec vos cours." /><ul className="mt-12 grid gap-x-10 md:grid-cols-2">{features.map(text => <li key={text} className="border-t border-ink-12 py-5">✓ <span className="ml-3">{text}</span></li>)}</ul><Link href="/fr/courses" className="mt-12 flex items-center justify-between gap-6 rounded-panel bg-ink-04 p-8"><span><span className="block text-2xl">Découvrez les cours MedWIZ</span><span className="mt-3 block text-ink-56">Lisez les 10 premières pages de chaque cours, classé par année.</span></span><span aria-hidden>↗</span></Link></div></Section>
    <Section id="series"><div className="shell"><SectionHeader eyebrow="La collection" title="Écrite année après année." intro="Chaque carnet couvre une matière d’une année. Les éditions paraissent au fil de leur rédaction, en commençant par la première année de médecine, puis en élargissant la collection à la pharmacie et à la chirurgie dentaire." /><div className="mt-12"><ButtonLink href="/fr/books" variant="outline">Parcourir le catalogue</ButtonLink></div></div></Section>
    <Section id="audience"><div className="shell"><SectionHeader eyebrow="Pour vous" title="C’est pour vous si…" /><ul className="mt-12 text-xl">{['vous étudiez la médecine, la pharmacie ou la chirurgie dentaire', 'vous cherchez des notes bien organisées', 'vous ne voulez plus recopier tous vos cours', 'vous préférez comprendre plutôt que mémoriser'].map(item => <li key={item} className="border-t border-ink-12 py-6">{item}</li>)}</ul></div></Section>
    <Section id="testimonials"><div className="shell"><SectionHeader eyebrow="Les étudiants en parlent" title="De petites pages. Un vrai changement." /><div className="mt-14 grid gap-8 md:grid-cols-3">{[['The Wiz m’a fait gagner des heures chaque semaine.', 'Lina B.', 'Première année de médecine'], ['J’avais enfin tout au même endroit.', 'Karim M.', 'Première année de médecine'], ['J’aurais aimé l’avoir dès le premier jour.', 'Sarah D.', 'Deuxième année de médecine']].map(([quote,name,detail]) => <figure key={name} className="rounded-panel border border-ink-12 p-8"><blockquote className="text-xl">« {quote} »</blockquote><figcaption className="mt-8 text-sm">{name}<span className="mt-2 block text-ink-56">{detail}</span></figcaption></figure>)}</div></div></Section>
    <Section id="about"><div className="shell max-w-4xl"><p className="type-eyebrow">À l’origine</p><blockquote className="mt-8 text-3xl leading-relaxed">« Créé par un étudiant en médecine qui voulait un carnet associant des résumés concis à de l’espace pour construire sa propre compréhension. »</blockquote><p className="mt-8 text-ink-56">The Wiz · Fondateur, étudiant en médecine</p></div></Section>
    <Section id="order"><div className="shell"><SectionHeader eyebrow="Commander" title="Commencez par l’édition disponible." intro="Une édition est disponible. Les autres carnets de la collection sont en préparation." /><div className="mt-12 max-w-2xl"><BookCard book={book} locale="fr" /></div><p className="mt-8 text-ink-56">La commande en ligne et l’inscription aux listes d’attente ne sont pas encore disponibles sur la version française.</p></div></Section>
    <Section id="faq"><div className="shell"><SectionHeader eyebrow="FAQ" title="Vos questions, nos réponses." /><div className="mt-12">{frenchFaqs.map(([question,answer]) => <details key={question} className="group border-t border-ink-12 py-6"><summary className="cursor-pointer text-lg">{question}</summary><p className="mt-5 max-w-3xl leading-relaxed text-ink-56">{answer}</p></details>)}</div></div></Section>
  </>;
}
